Add categorize function and tests
UBC-MDS/pylaundry pull request #30
Opened 2020-03-03 03:20 UTC by cgostic

I'm not too sure about the .lock file... can someone advise if I should be committing it?

2020-03-03 03:27 UTC, cgostic commented
See the issue below for my reasoning!

https://github.com/UBC-MDS/pylaundry/issues/31

2020-03-06 00:46 UTC, amank90 requested changes

2020-03-06 00:46 UTC, amank90 commented on pylaundry/categorize.py
> +import datetime
```suggestion

```

2020-03-06 00:47 UTC, amank90 requested changes

2020-03-06 00:47 UTC, amank90 commented on pylaundry/categorize.py
>      column_categories -- dict
```suggestion
    column_dict -- dict
```

2020-03-06 00:55 UTC, amank90 approved these changes

2020-03-06 00:56 UTC, merged