transform_function's first draft
UBC-MDS/pylaundry pull request #36
Opened 2020-03-05 05:51 UTC by arunmarria

The function is in its initial stage, I will keep on updating this PR by making necessary changes.

2020-03-05 06:07 UTC, amank90 commented on pylaundry/transform_columns.py
> +                              columns= X_train.columns)
```suggestion
Can change the X_train and X_test to X_train_transform and X_test_transform respectively
```

2020-03-06 00:25 UTC, amank90 commented on pylaundry/transform_columns.py
> +                              index = X_test.index,
```suggestion

#Change X_test and X_train
```

2020-03-06 00:58 UTC, zanderhinton requested changes
Function looks very good, and is written very clean and easy to read, great! 
I have suggested a few minor editing changes, as well as adding in one additional edge case check to confirm columns are the same for train and test sets.

2020-03-06 00:58 UTC, zanderhinton commented on pylaundry/transform_columns.py
> +        A pandas dataframe for training set
```suggestion
        A pandas dataframe for test set
```

2020-03-06 00:58 UTC, zanderhinton commented on pylaundry/transform_columns.py
> +    X_test = X_test
```suggestion
```

2020-03-06 00:58 UTC, zanderhinton commented on pylaundry/transform_columns.py
> +    assert isinstance(X_test, pd.DataFrame), "X_test should be a data frame"
```suggestion
    assert isinstance(X_test, pd.DataFrame), "X_test should be a DataFrame"
```

2020-03-06 00:58 UTC, zanderhinton commented on pylaundry/transform_columns.py
> +
```suggestion
    # Check train set and test set columns are the same
    assert np.array_equal(train_df.columns, test_df.columns), "train_df and test_df must have the same columns"
```

2020-03-06 17:16 UTC, zanderhinton approved these changes
New updates based on code review look  good!

2020-03-06 17:16 UTC, merged